### ISSUE TITLE
Error:  Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by bahrus** [web-padawan/api-viewer-element#13]
This could be a symptom of something wrong on my end, but this page:

https://bahrus.github.io/api-viewer/index.html?npmPackage=xtal-frappe-chart&jsPath=xtal-frappe-chart-example1.js

gives error

Error:  Cannot read property 'replace' of undefined

when clicking on the demo option.

**Comment by web-padawan** [comment]
Thanks for the issue. Fixed by ef7537c12a3a5ea9485645385f05fae2a55c722e and released as 0.3.4
