### ISSUE TITLE
Ability to remove demo functionality

### ISSUE THREAD

**Issue by p-ob** [web-padawan/api-viewer-element#14]
Before I start the work to add this feature, I wanted to see if this is something this project would even want to support. We're using this component to render our documentation for API-driven web components, and as our documentation site doesn't have access to our APIs, we'd like to remove the demo entirely.

Thinking something as easy as `<api-viewer no-demo src="./custom-element.json"></api-viewer>`.

**Comment by web-padawan** [comment]
Thanks for the issue. This is something that I was planning to do in the next release.

The idea that I have at the moment is to refactor the components and provide 3 entrypoints:

- `api-docs` for API docs only (this is what you need)
- `api-demo` for live playground only
- `api-viewer` for both

**Comment by web-padawan** [comment]
Done by #33 and will be released as part of `0.4` version later this week.
