### ISSUE TITLE
data-target="host" in demo template broken

### ISSUE THREAD

**Issue by woutervroege** [web-padawan/api-viewer-element#16]
Hi man,

I'm trying to add default properties to a demo using `data-target="host"`. Unfortunately, it seems to ignore this and falls back to `slot`. Furthermore, the README mentions both data-target` and `data-type` (none of which works though).

**Comment by web-padawan** [comment]
Hi, thanks for reporting. Updated the README to use `data-target` consistently.

Note that you must set `data-element` in order to make the template work.
Can you check that you have it in your code?

**Comment by web-padawan** [comment]
Fall back to "slot" is actually caused by this line:
https://github.com/web-padawan/api-viewer-element/blob/e2822756f2b5434b55311aa56508835facec0abd/src/lib/utils.ts#L24

I will change this in`0.4.0` so the component will throw if no `data-target` is set.

**Comment by web-padawan** [comment]
Done by #25 and will be included to the upcoming `0.4.0` release.
