### ISSUE TITLE
Feature: allow to pass the api data directly to the element

### ISSUE THREAD

**Issue by daKmoR** [web-padawan/api-viewer-element#18]
if the data of `custom-elements.json` is not available as file but only as a javascript object (or if I want to fetch it/extract it from somewhere else) then it would be nice to be able to set the data directly.

**Comment by web-padawan** [comment]
Thanks, this is a valid point. There should support for fetching data separately.

I'm planning to work more actively on `api-viewer` element again very soon. 
Will add this to my personal TODO list for the next minor version.

**Comment by christophe-g** [comment]
@web-padawan - this is a fantastic component ! I was hoping smth like it (completely web-component based, lightweight and playing well with a no build step approach) would emerge after a disappointing (hence short) use of storybook.
Many thanks.

**Comment by web-padawan** [comment]
Done by #24 and will be included to the upcoming `0.4.0` release.
