### ISSUE TITLE
unpkg, pika web support

### ISSUE THREAD

**Issue by bahrus** [web-padawan/api-viewer-element#2]
Component looks really nice!

I tried using this component using cdn support.

You can see my attempts here:  https://github.com/bahrus/hypo-link/blob/master/demo/syntax.html

One of the attempts is commented out.

Neither worked, for different reasons.

Hoping this can be fixed (if it hasn't already).

**Comment by web-padawan** [comment]
Thanks for the issue. The problem is most likely related to the fact that `marked` and `prismjs` do not provide ES module version - this is what Pika uses per `module` field in `package.json`.

See also https://github.com/markedjs/marked/issues/1288

If you know any better replacement for these libraries, please let me know and I will give it a try.

**Comment by web-padawan** [comment]
Good news: `marked` will support ES modules in the upcoming 0.8.0 release: https://github.com/markedjs/marked/pull/1571

I will update to that version alongside with the new `web-component-analyzer`.

**Comment by web-padawan** [comment]
Looks like the `illuminate-js` (which is written in TS and supports ES modules) can be used instead of `prismjs`. My only concern is that Illuminate is alpha and does not seem to be maintained.

https://github.com/vkbansal/illuminate-js

**Comment by web-padawan** [comment]
Good news: `marked` 0.8.0 is now released with ES modules
Bad news: they have removed the `"module"` field 😞 

Submitted pikapkg/analyze-npm#9 to discuss possible alternatives.

**Comment by web-padawan** [comment]
I have released `0.3.0` which adds https://unpkg.com CDN support.

Regarding `pika`, we should focus on fixing the issue mentioned above.
So let me close this issue for now and continue discussion there.
