### ISSUE TITLE
Provide option to display Live Playground by default

### ISSUE THREAD

**Issue by SPrinss** [web-padawan/api-viewer-element#3]
Thanks for this initiative!

I'd like to have the option to set the ApiViewerContent's `section` property.

When using `--watch` on `es-dev-server` the server reloads on every save, which is great, but I'd rather see my changes in the 'Live playground' than in the 'API docs viewer'.

Thanks again!

**Comment by web-padawan** [comment]
Thanks! That's a great idea, and the `section` property name seems good to me.
Will implement that and ship in the next release.

**Comment by web-padawan** [comment]
This is now released as `0.2.5` version.
