### ISSUE TITLE
Ability to customize demos and code snippets

### ISSUE THREAD

**Issue by juliexiong** [web-padawan/api-viewer-element#34]
I want to be able to provide my own demos and code snippets instead of rely on `api-viewer-element` to automatically generate them. They don't always come out accurate.

Here are my use-cases:
1. I have 3 types of checkboxes within one custom element, but only one example is shown. I would like to show all three.

```html
<!-- regular checkbox -->
<checkbox>Sign me up for daily emails</checkbox>

<!-- inline checkbox -->
<checkbox inline>Electronics</checkbox>

<!-- tile checkbox -->
<checkbox tile>R&B</checkbox tile>

<!-- api-viewer-element only shows the regular checkbox -->
<checkbox>Text me</checkbox>
```
2. I have a custom button dropdown menu that requires you to slot in `<button>`s or `<a>`s, but the demo shows using `<div>`s, which is incorrect.

```html
<!-- correct implementation -->
<button-dropdown>
  Actions
  <button slot="option">Download CSV</button>
  <button slot="option">Download Excel</button>
  <a href="#" slot="option">Email</a>
  <button slot="option">Print</button>
</button-dropdown>

<!-- api-viewer-viewer is generating this, which is incorrect -->
<button-dropdown>
  Actions
  <div slot="option">Download CSV</div>
  <div slot="option">Download Excel</div>
  <div slot="option">Email</div>
  <div slot="option">Print</div>
</button-dropdown>

**Comment by web-padawan** [comment]
Hello. The component has some configuration using templates.

> 2. I have a custom button dropdown menu

You can use `<template>` for this:

```html
<api-viewer>
  <template data-element="button-dropdown" data-target="slot">
    Actions
    <button slot="option">Download CSV</button>
    <button slot="option">Download Excel</button>
    <a href="#" slot="option">Email</a>
    <button slot="option">Print</button>
  </template>
</api-viewer>
```

Regarding the other request:

> 1. I have 3 types of checkboxes within one custom element

This is currently only possible with knobs. So you document `inline` and `tile` as boolean properties, then there will be checkboxes for each of them that user can toggle.

Also, in the upcoming `0.4.0` release there will be prefix & suffix slots (#27).
So, if you want to have static snippets, you will be able to do it like this:

```html
<api-viewer>
  <template data-element="my-checkbox" data-target="prefix">
    <my-checkbox inline>Inline checkbox</my-checkbox>
  </template>
  <template data-element="my-checkbox" data-target="suffix">
    <my-checkbox tile>Tile checkbox</my-checkbox>
  </template>
</api-viewer>
```

Is that something that could cover your cases?

**Comment by juliexiong** [comment]
Ah, my mistake. I'm using `<api-viewer-element>` with Gridsome so I didn't realize I had a `<template>` nesting situation where the inner `<template>` was not being activated as a result.

```html
<template>
  <api-viewer-element src="./custom-elements.json">
    <template data-element="button-dropdown" data-target="slot">
      Actions
      <button slot="option">Download CSV</button>
      <button slot="option">Download Excel</button>
      <a href="#" slot="option">Email</a>
      <button slot="option">Print</button>
    </template>
  </api-viewer-element>
</template>
```

**Comment by web-padawan** [comment]
Now I see. In 0.4 it will be possible to pass your templates, by extending a component:

```js
import { customElement } from 'lit-element';
import { ApiViewerBase } from 'api-viewer-element/lib/api-viewer-base.js';
import styles from 'api-viewer-element/lib/api-viewer-styles.js';
import { setTemplates } from 'api-viewer-element/lib/lib/utils.js';

export class MyApiViewer extends ApiViewerBase {
  static get styles() {
    return styles;
  }

  firstUpdated() {
    const templates = []; // store templates somewhere
    setTemplates(templates);
  }
}

customElements.define('my-api-viewer', MyApiViewer)
```

That should solve the case where placing `template` elements as children doesn't work.

**Comment by web-padawan** [comment]
I have released a new version today, which has public `setTemplates` method. Can you try it?

**Comment by web-padawan** [comment]
As mentioned above, it's now possible to customise how templates are loaded. Closing as stale.
