### ISSUE TITLE
Live demo: Element provided as slotted content multiple times has it's slot name overwritten

### ISSUE THREAD

**Issue by SPrinss** [web-padawan/api-viewer-element#38]
Perhaps I'm missing something but I'm unable to show slotted content in the correct named slot="some-name" in the live demo. 

Say I have the following setup:
```
<some-footer>
      <some-list slot="one">
            <li>Info</li>
            <li><a href="#">Some Link 1</a></li>
            <li><a href="#">Some Link 2</a></li>
            <li><a href="#">Some Link 3</a></li>
            <li><a href="#">Some Link 4</a></li>
            <li><a href="#">Some Link 5</a></li>            
      </some-list>
      <some-list slot="two">
            <li>Info</li>
            <li><a href="#">Some Link 1</a></li>
            <li><a href="#">Some Link 2</a></li>
            <li><a href="#">Some Link 3</a></li>
            <li><a href="#">Some Link 4</a></li>
            <li><a href="#">Some Link 5</a></li>            
      </some-list>
</some-footer>
```

Where `some-footer` is:
```
 * @slot one
 * @slot two

<footer>
        
     <nav>
       <slot name="one"></slot>
     </nav>

    <nav>
       <slot name="two"></slot>          
    </nav>
</footer>

```

What I see if I use `<template type="host">` is the names of the slots defined in the docjs (e.g. @slot one) instead of the slotted content. 

If I use `<template type="slot">` all slotted content is added to the last defined slot (e.g. name="two").

**Comment by SPrinss** [comment]
Apologies, the problem is somewhat different than I expected. 

Using `<ul>` instead of `<some-list>` the slotted content does render correctly. 

When using `<some-list slot="one">` and `<some-list slot="two">` both `some-list` elements have `slot="two"` in the DOM.

**Comment by web-padawan** [comment]
Hi, thanks for the issue. Content for slots should be added using `<template data-target="slot">`

I didn't test how that works with named slots though. Will investigate.

**Comment by SPrinss** [comment]
Sorry, this bug was caused by using our own [html-element-property-mixins](https://github.com/woutervroege/html-element-property-mixins/) in combination with lit-html (which api-viewer-demo uses). 
I tested the functionality in an isolated html file (without lit-html). Should have tested a bit more before filing an issue, my apologies.

**Comment by web-padawan** [comment]
Does this mean that component does npt work in `lit-html` template for you?

It would be nice if you could provide a small reproduction.

**Comment by SPrinss** [comment]
Yes.. we're still developing the mixins and are going to investigate the issue tomorrow. 

So this issue doesn't have anything to do with api-viewer-element except that the api-viewer-demo uses lit-html. 

Still interested in a reproduction?

**Comment by web-padawan** [comment]
Sure, this sounds like worth investigating to me.

**Comment by SPrinss** [comment]
We were calling super.connectedCallback() in our base element (which is rather a weird thing to do :) ). 

The mixins handle a lot of stuff on connectedCallback (like setting attributes) so I guess somehow the scope got changed by calling super.connectedCallback(). 
Everything working well now, including the api-viewer-demo.

Apologies again for wasting your time.

**Comment by web-padawan** [comment]
No worries, glad that you sorted it out!
