### ISSUE TITLE
Add `selected-tag` to public API

### ISSUE THREAD

**Issue by woutervroege** [web-padawan/api-viewer-element#5]
Hi,

Thanks for the great work :)
I'd be great if `<api-viewer>` has a 'selected-tag' prop, which then could be bound (using its index) to the `selected` in `<api-viewer-contents>`. 

This would potentially enable binding the 'selected-tag' property to url query / hash params. This would be really powerful when using watch & reload scripts and returning to the same doc and/or demo page.

**Comment by web-padawan** [comment]
Thanks for the issue. I agree it makes a lot of sense. Will expose that property in the next release.

**Comment by web-padawan** [comment]
The `selected` string property is now released as `0.2.6` version.
