### ISSUE TITLE
Support for Custom Elements Manifest 1.0.0?

### ISSUE THREAD

**Issue by Westbrook** [web-padawan/api-viewer-element#61]
I'm checking in to see if you have any plans to support https://www.npmjs.com/package/custom-elements-manifest and it's 1.0.0 release? We just had a great discussion with the [w3c Web Components Community Group](https://github.com/w3c/webcomponents-cg) where many attendees praised you great work here and thought it would be great to see motion in this regard. I'm sure if you didn't feel you had the time that we could could find a community member excited to submit a PR with agreed upon modification in this area.

**Comment by web-padawan** [comment]
Hi, yes I'm going to take a look at the new JSON format soon. This will likely require some updates to the component.

**Comment by web-padawan** [comment]
This is available in 0.6.0. Please note, the API might change a bit, e.g. support for methods is still missing.
