### ISSUE TITLE
Pass params to the displayed element

### ISSUE THREAD

**Issue by sebastianroming** [web-padawan/api-viewer-element#7]
First: thanks for this great repo! 
Second:

I created a mono-repo for some webcomponents, like `button`, `input`, etc. 
Also the repo holds some complex elements based on these single components, like a `form` element which uses `button` and `input`.

The form is populated via an attribute, e.g.
```
<ui-form inputs='[{"type":"input","label":"Test label"}]'></ui-form>
```
and the corresponding input fields are generated.

How is it possible to pass attributes to the `api-viewer-element`? If I use it like this:
```
<template data-element="ui-form">
    <ui-form inputs='[{"type":"input","label":"Test label"}]'></ui-form>
</template>
```
the source in the `api-viewer-element` is shown like this and the `ui-form` gets rendererd twice:
```
<ui-form>  
  <ui-form inputs='[{"type":"input","label":"Test label"}]'></ui-form>
</ui-form>
```

But nothing is displayed... Did I miss something or is this simply not possible?

**Comment by web-padawan** [comment]
Thanks for the issue. This isn't currently supported, but I think there should be such a feature.

As you noticed, the `template` is currently used for slotted content only. 
We can add another attribute to use it for element itself, e.g.  `data-type="host"`

**Comment by sebastianroming** [comment]
Thanks for the quick reply. Yes, I've seen it and that made me sort of thinking if there's a possiblity ;-) 
Would be great if this option will follow in any of the next versions 👍
