### ISSUE TITLE
Support for lit 2 components

### ISSUE THREAD

**Issue by baermathias** [web-padawan/api-viewer-element#98]
I guess support for `lit` 2.x components is not available yet? I tried to run the `web-component-analyzer` on a `lit` project to create a `custom-elements.json` file, but it didn't work out. It only works on `lit-element` projects / components. Are there plans to adopt `lit` 2.x ?

**Comment by web-padawan** [comment]
This needs #61 which will switch from `web-component-analyzer` to `@custom-element-manifest/analyzer`.
I'm planning to work on it this week and release a next 0.x minor version with Lit 2 components support.

**Comment by saitam1** [comment]
Any news on this?

**Comment by web-padawan** [comment]
Hi, sorry about the delay. I was a bit busy but tomorrow I will get back to making finishing touches to the docs. Then I also want to fix two small bugs. If everything goes well, I hope to make a new release on Monday.

**Comment by web-padawan** [comment]
This is available in 0.6.0. Please note, the API might change a bit, e.g. support for methods is still missing.
